Update browser option untuk non-chrome user
bebasid/bebasid pull request #287
Opened 2021-02-08 09:11 UTC by fijar-lazuardy

Update untuk non-chrome user.
Sejauh ini hanya masih tersedia 3 opsi: Google Chrome, Firefox, dan Brave Browser.

Tested on: 
OS:       Ubuntu 20.04. LTS
Kernel: 5.8.0-41-generic

Test preview
Command:
![image](https://user-images.githubusercontent.com/32705957/107198591-dd0fc880-6a27-11eb-8d2d-3dcd0cbf85ff.png)

Browser:
![image](https://user-images.githubusercontent.com/32705957/107198836-30821680-6a28-11eb-8ff8-9cdcd685b121.png)

Tmux tunnel
![image](https://user-images.githubusercontent.com/32705957/107198692-06c8ef80-6a28-11eb-936d-c81eb12bdb1b.png)

2021-02-08 13:37 UTC, icaksh requested changes
udah bagus konsepnya cuma ada review:
1. Firefox nggak bakal jalan karena flagsnya berbeda (https://linux.die.net/man/1/firefox)

ada dua fix untuk hal ini, yaitu bisa dihapus untuk firefox atau menambah setting biar firefox dapat jalan sebelum saya merge

Terima kasih atas partisipasinya

2021-02-08 13:37 UTC, icaksh commented on releases/bebasid.sh
> +      tmux send-keys -t 2 "$browser netflix.com --proxy-server=127.0.0.1:$random" Enter
bagian ini hanya work untuk browser based chromium..
firefox harus ada profil

2021-02-08 15:56 UTC, fijar-lazuardy commented on releases/bebasid.sh
> +      tmux send-keys -t 2 "$browser netflix.com --proxy-server=127.0.0.1:$random" Enter
menarik, soalnya tadi saya coba di machine saya work just fine, tapi harusnya gampang di-fix sih

2021-02-08 16:15 UTC, fijar-lazuardy reviewed
Untuk fix sementara harusnya ini work just fine sih

2021-02-08 16:15 UTC, fijar-lazuardy commented on releases/bebasid.sh
> +      fi
Karena sepertinya ga bisa nge-list profile Firefox langsung dari terminal, alternatifnya saya pakai flag -ProfileManager biar user bisa pilih manual profile saat launch browser

Testing: 
![image](https://user-images.githubusercontent.com/32705957/107246821-3a753b00-6a63-11eb-9949-3c7e81262265.png)

Pop-up prompt:
![image](https://user-images.githubusercontent.com/32705957/107246751-27626b00-6a63-11eb-893f-00ad93e44d03.png)

![image](https://user-images.githubusercontent.com/32705957/107246897-4f51ce80-6a63-11eb-94e8-ccaa731cd7b6.png)

Test buka reddit:
![image](https://user-images.githubusercontent.com/32705957/107246949-5e388100-6a63-11eb-8f12-85d4d6ef3bb1.png)

2021-02-09 12:57 UTC, icaksh approved these changes

2021-02-09 12:58 UTC, icaksh commented
Dah fixed

2021-02-09 12:58 UTC, merged